/* clang-format off */
/*
 * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
/* clang-format on */

#include <mip_heuristics/deterministic_calibrator/bp_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/calibrator.hpp>
#include <mip_heuristics/deterministic_calibrator/fj_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/fp_verify_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/gpu_features.hpp>
#include <mip_heuristics/deterministic_calibrator/mp_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/pdlp_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/repair_harness.hpp>
#include <mip_heuristics/deterministic_calibrator/work_features.hpp>

#include <mip_heuristics/deterministic_calibrator/device_model.hpp>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace cuopt::linear_programming::detail::calib;

namespace {

// The user-approved calibration set (datasets/mip/miplib2017): spread over size / sparsity /
// row-size variance / integer fraction.
const std::vector<std::string> kInstances = {
  "gen-ip054",
  "gmu-35-50",
  "cvs16r128-89",
  "sct2",
  "tr12-30",
  "seymour1",
  "nw04",
  "uccase9",
  "ns1208400",
  "neos-3004026-krka",
  "bab2",
  "nursesched-medium-hint03",
};

// ---- FJ: single linear model ----
void run_fj(const std::string& dataset_dir, std::string out_header)
{
  std::vector<calibration_sample_t> samples;
  for (const auto& name : kInstances) {
    const std::string path = dataset_dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      samples.push_back(run_fj_calibration_sample(path, name));
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  if (samples.size() < 2) {
    std::printf("Not enough samples (%zu)\n", samples.size());
    return;
  }
  const auto names = fj_feature_names();
  work_calibrator_t cal;
  auto result = cal.fit(samples, names.size(), work_calibrator_t::options_t{});
  std::printf("\n=== fj fit ===\nsamples=%zu CV=%.4f converged=%s\n",
              samples.size(),
              result.cv,
              result.converged ? "yes" : "no");
  for (std::size_t i = 0; i < result.coeffs.size(); ++i) {
    std::printf("  coeff[%s] = %.6g\n", names[i].c_str(), result.coeffs[i]);
  }
  if (out_header.empty()) {
    out_header = "cpp/src/mip_heuristics/deterministic_calibrator/generated/fj_work_coeffs.hpp";
  }
  emit_coeffs_header(out_header, "fj", names, result, samples);
  std::printf("Wrote %s\n", out_header.c_str());
}

// ---- BP: per-kernel models (activity + bounds-update), summed at runtime ----
void emit_two_kernel_header(const std::string& path,
                            const std::string& algo,
                            const std::vector<std::string>& names,
                            const calibration_result_t& act,
                            const calibration_result_t& upd,
                            double combined_cv,
                            double excess_warp_loads_threshold)
{
  std::ofstream f(path);
  f << "/* clang-format off */\n/*\n";
  f << " * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All "
       "rights reserved.\n";
  f << " * SPDX-License-Identifier: Apache-2.0\n *\n";
  f << " * AUTO-GENERATED by mip_work_calibrator. Do not edit by hand.\n";
  f << " * Algorithm: " << algo << " (per-kernel: activity + bounds-update)\n";
  f << " * Combined per-iteration CV (measured/predicted): " << combined_cv << "\n";
  f << " * activity sub-fit CV: " << act.cv << "   bounds-update sub-fit CV: " << upd.cv << "\n";
  f << " */\n/* clang-format on */\n#pragma once\n\n#include <array>\n\n";
  f << "namespace cuopt::linear_programming::detail::calib {\n\n";
  f << "// Saturation hinge: excess_warp_loads = max(0, changed_warp_loads - threshold).\n";
  f << "constexpr double " << algo
    << "_excess_warp_loads_threshold = " << excess_warp_loads_threshold << ";\n\n";
  auto emit = [&](const std::string& var, const calibration_result_t& r) {
    f << "constexpr std::array<double, " << r.coeffs.size() << "> " << var << " = {\n";
    for (std::size_t i = 0; i < r.coeffs.size(); ++i) {
      f << "  " << r.coeffs[i] << ",  // " << (i < names.size() ? names[i] : "feature") << "\n";
    }
    f << "};\n\n";
  };
  emit(algo + "_activity_work_coeffs", act);
  emit(algo + "_update_work_coeffs", upd);
  f << "}  // namespace cuopt::linear_programming::detail::calib\n";
}

// Combined per-iteration CV: pair activity[i]+update[i] (same feature point).
double combined_cv_of(const std::vector<calibration_sample_t>& act,
                      const std::vector<calibration_sample_t>& upd,
                      const calibration_result_t& act_fit,
                      const calibration_result_t& upd_fit)
{
  double mean = 0.0;
  std::vector<double> ratios(act.size());
  for (std::size_t i = 0; i < act.size(); ++i) {
    const double pred =
      predict_work(act_fit.coeffs, act[i].features) + predict_work(upd_fit.coeffs, upd[i].features);
    const double meas = act[i].measured_time_per_iter + upd[i].measured_time_per_iter;
    ratios[i]         = meas / pred;
    mean += ratios[i];
  }
  mean /= static_cast<double>(act.size());
  double var = 0.0;
  for (double r : ratios) {
    var += (r - mean) * (r - mean);
  }
  var /= static_cast<double>(act.size());
  return std::sqrt(var) / mean;
}

// Shared per-kernel (activity + bounds-update) fit with a saturation hinge, used by bp and mp.
void fit_two_kernel(const std::string& algo,
                    std::vector<calibration_sample_t> act,
                    std::vector<calibration_sample_t> upd,
                    std::string out_header)
{
  if (act.size() < 2) {
    std::printf("Not enough samples (%zu)\n", act.size());
    return;
  }
  auto names = bp_feature_names();
  // changed_warp_loads is the last base bp feature; the saturation hinge is built from it.
  const std::size_t warp_idx = names.size() - 1;
  names.push_back("excess_warp_loads");  // max(0, warp_loads - T): reduction beyond hidden capacity

  // Append the hinge feature max(0, warp_loads - T) to every sample (same T for act and upd).
  auto augment = [&](std::vector<calibration_sample_t> s, double T) {
    for (auto& x : s) {
      x.features.push_back(std::max(0.0, x.features[warp_idx] - T));
    }
    return s;
  };

  work_calibrator_t cal;
  // Grid-search the saturation threshold T (hidden parallel reduction capacity, in warp-loads).
  const std::vector<double> Ts = {0, 2000, 4000, 8000, 16000, 32000, 64000, 128000};
  double best_cv               = 1e30;
  double best_T                = 0.0;
  calibration_result_t act_fit, upd_fit;
  std::vector<calibration_sample_t> best_act, best_upd;
  for (double T : Ts) {
    auto aT   = augment(act, T);
    auto uT   = augment(upd, T);
    auto af   = cal.fit(aT, names.size(), work_calibrator_t::options_t{});
    auto uf   = cal.fit(uT, names.size(), work_calibrator_t::options_t{});
    double cv = combined_cv_of(aT, uT, af, uf);
    std::printf("  [grid] T=%.0f -> combined CV=%.4f\n", T, cv);
    if (cv < best_cv) {
      best_cv  = cv;
      best_T   = T;
      act_fit  = af;
      upd_fit  = uf;
      best_act = std::move(aT);
      best_upd = std::move(uT);
    }
  }
  act                      = std::move(best_act);
  upd                      = std::move(best_upd);
  const double combined_cv = best_cv;
  std::printf("  [grid] best T=%.0f combined CV=%.4f\n", best_T, best_cv);

  std::printf("\n=== %s fit (per-kernel) ===\n", algo.c_str());
  std::printf("samples=%zu  activity CV=%.4f  update CV=%.4f  COMBINED CV=%.4f\n",
              act.size(),
              act_fit.cv,
              upd_fit.cv,
              combined_cv);
  std::printf("activity coeffs:\n");
  for (std::size_t i = 0; i < act_fit.coeffs.size(); ++i) {
    std::printf("  [%s] = %.6g\n", names[i].c_str(), act_fit.coeffs[i]);
  }
  std::printf("update coeffs:\n");
  for (std::size_t i = 0; i < upd_fit.coeffs.size(); ++i) {
    std::printf("  [%s] = %.6g\n", names[i].c_str(), upd_fit.coeffs[i]);
  }
  std::printf("\ncombined per-point ratio (measured/predicted, want ~1):\n");
  for (std::size_t i = 0; i < act.size(); ++i) {
    const double pred =
      predict_work(act_fit.coeffs, act[i].features) + predict_work(upd_fit.coeffs, upd[i].features);
    const double meas = act[i].measured_time_per_iter + upd[i].measured_time_per_iter;
    std::printf(
      "  %-32s meas=%.3e pred=%.3e ratio=%.3f\n", act[i].instance.c_str(), meas, pred, meas / pred);
  }

  if (out_header.empty()) {
    out_header =
      "cpp/src/mip_heuristics/deterministic_calibrator/generated/" + algo + "_work_coeffs.hpp";
  }
  emit_two_kernel_header(out_header, algo, names, act_fit, upd_fit, combined_cv, best_T);
  std::printf("\nWrote %s\n", out_header.c_str());
}

void run_bp(const std::string& dataset_dir, const std::string& out_header)
{
  std::vector<calibration_sample_t> act, upd;
  for (const auto& name : kInstances) {
    const std::string path = dataset_dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      auto s = run_bp_calibration_samples(path, name);
      act.insert(act.end(), s.activity.begin(), s.activity.end());
      upd.insert(upd.end(), s.update.begin(), s.update.end());
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  fit_two_kernel("bp", std::move(act), std::move(upd), out_header);
}

// multi_probe: activity sub-kernel hinges on changed-constraint warp-loads, bounds-update
// sub-kernel hinges on changed-variable warp-loads (each its own threshold; 2D grid).
void run_mp(const std::string& dataset_dir, std::string out_header)
{
  std::vector<calibration_sample_t> act, upd;
  for (const auto& name : kInstances) {
    const std::string path = dataset_dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      auto s = run_mp_calibration_samples(path, name);
      act.insert(act.end(), s.activity.begin(), s.activity.end());
      upd.insert(upd.end(), s.update.begin(), s.update.end());
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  if (act.size() < 2) {
    std::printf("Not enough samples (%zu)\n", act.size());
    return;
  }
  auto names                = mp_feature_names();
  const std::size_t cons_ix = mp_cons_warp_index();
  const std::size_t vars_ix = mp_vars_warp_index();

  // Single model on TOTAL per-iteration time (activity + bounds-update). Avoids the per-kernel
  // split noise from timing two tiny kernels separately. Two saturation hinges: constraint-side
  // (activity) and variable-side (update).
  std::vector<calibration_sample_t> tot(act.size());
  for (std::size_t i = 0; i < act.size(); ++i) {
    tot[i].instance               = act[i].instance;
    tot[i].features               = act[i].features;
    tot[i].measured_time_per_iter = act[i].measured_time_per_iter + upd[i].measured_time_per_iter;
  }
  auto augment2 = [&](std::vector<calibration_sample_t> s, double Tc, double Tv) {
    for (auto& x : s) {
      x.features.push_back(std::max(0.0, x.features[cons_ix] - Tc));
      x.features.push_back(std::max(0.0, x.features[vars_ix] - Tv));
    }
    return s;
  };

  work_calibrator_t cal;
  const std::vector<double> Ts = {0, 2000, 4000, 8000, 16000, 32000, 64000, 128000};
  double best_cv = 1e30, best_Tc = 0, best_Tv = 0;
  calibration_result_t best_fit;
  std::vector<calibration_sample_t> best_s;
  for (double Tc : Ts) {
    for (double Tv : Ts) {
      auto sT  = augment2(tot, Tc, Tv);
      auto fit = cal.fit(sT, names.size() + 2, work_calibrator_t::options_t{});
      if (fit.cv < best_cv) {
        best_cv  = fit.cv;
        best_Tc  = Tc;
        best_Tv  = Tv;
        best_fit = fit;
        best_s   = std::move(sT);
      }
    }
  }
  std::printf("\n=== mp fit (single model on total, 2D hinge) ===\n");
  std::printf("samples=%zu best T_cons=%.0f T_vars=%.0f  COMBINED CV=%.4f\n",
              best_s.size(),
              best_Tc,
              best_Tv,
              best_cv);
  auto names_out = names;
  names_out.push_back("excess_cons_warp_loads");
  names_out.push_back("excess_vars_warp_loads");
  for (std::size_t i = 0; i < best_fit.coeffs.size(); ++i)
    std::printf("  [%s] = %.6g\n", names_out[i].c_str(), best_fit.coeffs[i]);
  std::printf("\nper-point ratio (measured/predicted):\n");
  for (const auto& s : best_s) {
    const double pred = predict_work(best_fit.coeffs, s.features);
    std::printf("  %-28s meas=%.3e pred=%.3e ratio=%.3f\n",
                s.instance.c_str(),
                s.measured_time_per_iter,
                pred,
                s.measured_time_per_iter / pred);
  }
  if (out_header.empty()) {
    out_header = "cpp/src/mip_heuristics/deterministic_calibrator/generated/mp_work_coeffs.hpp";
  }
  std::ofstream f(out_header);
  f << "/* clang-format off */\n/*\n * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA "
       "CORPORATION & AFFILIATES. All rights reserved.\n * SPDX-License-Identifier: Apache-2.0\n "
       "*\n";
  f << " * AUTO-GENERATED by mip_work_calibrator. Do not edit by hand.\n";
  f << " * Algorithm: mp (single model on total per-iteration time, 2D saturation hinge)\n";
  f << " * Per-iteration CV: " << best_cv << "\n */\n/* clang-format on */\n#pragma once\n\n";
  f << "#include <array>\n\nnamespace cuopt::linear_programming::detail::calib {\n\n";
  f << "constexpr double mp_excess_cons_warp_threshold = " << best_Tc << ";\n";
  f << "constexpr double mp_excess_vars_warp_threshold = " << best_Tv << ";\n\n";
  f << "constexpr std::array<double, " << best_fit.coeffs.size() << "> mp_work_coeffs = {\n";
  for (std::size_t i = 0; i < best_fit.coeffs.size(); ++i)
    f << "  " << best_fit.coeffs[i] << ",  // " << (i < names_out.size() ? names_out[i] : "f")
      << "\n";
  f << "};\n\n}  // namespace cuopt::linear_programming::detail::calib\n";
  std::printf("\nWrote %s\n", out_header.c_str());
}

// ---- generic single-model fit with a saturation hinge on the last feature ----
void emit_single_hinge_header(const std::string& path,
                              const std::string& algo,
                              const std::vector<std::string>& names,
                              const calibration_result_t& r,
                              double threshold)
{
  std::ofstream f(path);
  f << "/* clang-format off */\n/*\n";
  f << " * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All "
       "rights reserved.\n";
  f << " * SPDX-License-Identifier: Apache-2.0\n *\n";
  f << " * AUTO-GENERATED by mip_work_calibrator. Do not edit by hand.\n";
  f << " * Algorithm: " << algo << "\n";
  f << " * CV (measured/predicted): " << r.cv << "\n */\n/* clang-format on */\n#pragma once\n\n";
  f << "#include <array>\n\nnamespace cuopt::linear_programming::detail::calib {\n\n";
  f << "// Saturation hinge: excess = max(0, " << names.back() << " - threshold).\n";
  f << "constexpr double " << algo << "_excess_warp_loads_threshold = " << threshold << ";\n\n";
  f << "constexpr std::array<double, " << r.coeffs.size() << "> " << algo << "_work_coeffs = {\n";
  for (std::size_t i = 0; i < r.coeffs.size(); ++i) {
    f << "  " << r.coeffs[i] << ",  // " << (i < names.size() ? names[i] : "feature") << "\n";
  }
  f << "};\n\n}  // namespace cuopt::linear_programming::detail::calib\n";
}

void run_single_hinge(const std::string& algo,
                      const std::vector<std::string>& base_names,
                      std::vector<calibration_sample_t> samples,
                      std::string out_header)
{
  if (samples.size() < 2) {
    std::printf("Not enough samples (%zu)\n", samples.size());
    return;
  }
  auto names                 = base_names;
  const std::size_t hinge_on = names.size() - 1;  // last feature (total warp loads)
  names.push_back("excess_warp_loads");

  auto augment = [&](std::vector<calibration_sample_t> s, double T) {
    for (auto& x : s) {
      x.features.push_back(std::max(0.0, x.features[hinge_on] - T));
    }
    return s;
  };

  work_calibrator_t cal;
  const std::vector<double> Ts = {0, 2000, 4000, 8000, 16000, 32000, 64000, 128000, 256000};
  double best_cv               = 1e30;
  double best_T                = 0.0;
  calibration_result_t best_fit;
  std::vector<calibration_sample_t> best_samples;
  for (double T : Ts) {
    auto sT  = augment(samples, T);
    auto fit = cal.fit(sT, names.size(), work_calibrator_t::options_t{});
    std::printf("  [grid] T=%.0f -> CV=%.4f\n", T, fit.cv);
    if (fit.cv < best_cv) {
      best_cv      = fit.cv;
      best_T       = T;
      best_fit     = fit;
      best_samples = std::move(sT);
    }
  }
  std::printf("\n=== %s fit ===\nsamples=%zu best T=%.0f CV=%.4f\n",
              algo.c_str(),
              best_samples.size(),
              best_T,
              best_cv);
  for (std::size_t i = 0; i < best_fit.coeffs.size(); ++i) {
    std::printf("  [%s] = %.6g\n", names[i].c_str(), best_fit.coeffs[i]);
  }
  std::printf("\nper-instance ratio (measured/predicted):\n");
  for (const auto& s : best_samples) {
    const double pred = predict_work(best_fit.coeffs, s.features);
    std::printf("  %-28s meas=%.3e pred=%.3e ratio=%.3f\n",
                s.instance.c_str(),
                s.measured_time_per_iter,
                pred,
                s.measured_time_per_iter / pred);
  }
  if (out_header.empty()) {
    out_header =
      "cpp/src/mip_heuristics/deterministic_calibrator/generated/" + algo + "_work_coeffs.hpp";
  }
  emit_single_hinge_header(out_header, algo, names, best_fit, best_T);
  std::printf("\nWrote %s\n", out_header.c_str());
}

void run_pdlp(const std::string& dataset_dir, const std::string& out_header)
{
  std::vector<calibration_sample_t> samples;
  for (const auto& name : kInstances) {
    const std::string path = dataset_dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      samples.push_back(run_pdlp_calibration_sample(path, name));
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  run_single_hinge("pdlp", pdlp_feature_names(), std::move(samples), out_header);
}

void run_repair(const std::string& dataset_dir, const std::string& out_header)
{
  std::vector<calibration_sample_t> samples;
  for (const auto& name : kInstances) {
    const std::string path = dataset_dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      auto s = run_repair_calibration_sample(path, name);
      samples.insert(samples.end(), s.begin(), s.end());
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  run_single_hinge("repair", repair_feature_names(), std::move(samples), out_header);
}

// ============================ multi-GPU dump / fit ============================
// Phase 1 (per GPU): `dump <algo> <dataset> <csv>` runs the harness on the current device and
// appends raw samples + the device descriptor to a CSV. Phase 2 (once): `fit <algo> <csv...>`
// loads every GPU's samples and fits ONE device-aware regression (device_model.hpp recipe), so the
// emitted coefficients transfer across GPUs.

struct dump_row_t {
  gpu_features_t g;
  std::string kernel;  // single | act | upd
  std::string instance;
  double measured;
  std::vector<double> feat;  // raw harness feature vector (feat[0] == 1 intercept)
  double max_row{0.0};       // longest constraint row (serialization count)
};

// Kernel-tagged raw samples for an algorithm on the current device.
std::vector<std::pair<std::string, calibration_sample_t>> collect_samples(const std::string& algo,
                                                                          const std::string& dir)
{
  std::vector<std::pair<std::string, calibration_sample_t>> out;
  for (const auto& name : kInstances) {
    const std::string path = dir + "/" + name + ".mps";
    std::printf("\n[instance] %s\n", name.c_str());
    std::fflush(stdout);
    try {
      if (algo == "fj") {
        out.emplace_back("single", run_fj_calibration_sample(path, name));
      } else if (algo == "pdlp") {
        out.emplace_back("single", run_pdlp_calibration_sample(path, name));
      } else if (algo == "repair") {
        for (auto& s : run_repair_calibration_sample(path, name))
          out.emplace_back("single", std::move(s));
      } else if (algo == "bp") {
        auto s = run_bp_calibration_samples(path, name);
        for (auto& x : s.activity)
          out.emplace_back("act", std::move(x));
        for (auto& x : s.update)
          out.emplace_back("upd", std::move(x));
      } else if (algo == "mp") {
        auto s = run_mp_calibration_samples(path, name);
        for (auto& x : s.activity)
          out.emplace_back("act", std::move(x));
        for (auto& x : s.update)
          out.emplace_back("upd", std::move(x));
      }
    } catch (const std::exception& e) {
      std::printf("  SKIP (%s)\n", e.what());
    }
  }
  return out;
}

void dump_mode(const std::string& algo, const std::string& dir, const std::string& csv)
{
  const gpu_features_t g = query_gpu_features(0);
  print_gpu_features(g);
  auto samples = collect_samples(algo, dir);
  std::ofstream f(csv, std::ios::app);
  for (const auto& [kernel, s] : samples) {
    f << g.name << ',' << g.mem_bandwidth_gb_s << ',' << g.sm_count << ',' << g.sm_clock_ghz << ','
      << g.l2_cache_mb << ',' << g.warp_capacity << ',' << algo << ',' << kernel << ','
      << s.instance << ',' << s.measured_time_per_iter << ',' << s.features.size();
    for (double x : s.features)
      f << ',' << x;
    f << ',' << s.max_row_nnz << '\n';  // trailing serialization count (longest row)
  }
  std::printf("\nAppended %zu samples to %s\n", samples.size(), csv.c_str());
}

std::vector<dump_row_t> load_rows(const std::vector<std::string>& csvs,
                                  const std::string& algo,
                                  const std::string& kernel)
{
  std::vector<dump_row_t> rows;
  for (const auto& path : csvs) {
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) {
      if (line.empty()) continue;
      std::vector<std::string> tok;
      std::stringstream ss(line);
      std::string t;
      while (std::getline(ss, t, ','))
        tok.push_back(t);
      if (tok.size() < 11) continue;
      if (tok[6] != algo || tok[7] != kernel) continue;
      dump_row_t r;
      std::snprintf(r.g.name, sizeof(r.g.name), "%s", tok[0].c_str());
      r.g.mem_bandwidth_gb_s  = std::stod(tok[1]);
      r.g.sm_count            = std::stod(tok[2]);
      r.g.sm_clock_ghz        = std::stod(tok[3]);
      r.g.l2_cache_mb         = std::stod(tok[4]);
      r.g.warp_capacity       = std::stod(tok[5]);
      r.kernel                = tok[7];
      r.instance              = tok[8];
      r.measured              = std::stod(tok[9]);
      const std::size_t nfeat = (std::size_t)std::stoul(tok[10]);
      for (std::size_t i = 0; i < nfeat && 11 + i < tok.size(); ++i)
        r.feat.push_back(std::stod(tok[11 + i]));
      if (11 + nfeat < tok.size()) r.max_row = std::stod(tok[11 + nfeat]);
      rows.push_back(std::move(r));
    }
  }
  return rows;
}

// CV of measured/predicted for a device-aware fit, optionally restricted to one GPU name.
double device_cv(const std::vector<dump_row_t>& rows,
                 const std::vector<double>& coeffs,
                 double hinge_k,
                 bool use_hinge,
                 const std::string& only_gpu = std::string())
{
  std::vector<double> ratios;
  for (const auto& r : rows) {
    if (!only_gpu.empty() && std::string(r.g.name) != only_gpu) continue;
    std::vector<double> raw(r.feat.begin() + 1, r.feat.end());  // drop intercept
    double excess = use_hinge ? std::max(0.0, raw.back() - hinge_k * r.g.warp_capacity) : 0.0;
    auto x        = device_terms(raw, r.g, excess, r.max_row);
    double pred   = predict_work(coeffs, x);
    if (pred <= 0.0) continue;
    ratios.push_back(r.measured / pred);
  }
  if (ratios.empty()) return 1e30;
  double mean = 0.0;
  for (double v : ratios)
    mean += v;
  mean /= (double)ratios.size();
  double var = 0.0;
  for (double v : ratios)
    var += (v - mean) * (v - mean);
  var /= (double)ratios.size();
  return std::sqrt(var) / mean;
}

// Single-kernel device-aware fit (fj has no hinge; pdlp/repair hinge on the last raw feature =
// total warp loads, threshold k * warp_capacity).
void fit_single_device(const std::string& algo, const std::vector<std::string>& csvs)
{
  auto rows = load_rows(csvs, algo, "single");
  if (rows.size() < 3) {
    std::printf("Not enough rows for %s (%zu)\n", algo.c_str(), rows.size());
    return;
  }
  const bool use_hinge = (algo != "fj");
  const std::vector<double> ks =
    use_hinge ? std::vector<double>{0, 0.5, 1, 2, 4, 8, 16, 32} : std::vector<double>{0};

  std::size_t n_raw   = rows.front().feat.size() - 1;
  std::size_t n_terms = device_term_count(n_raw);

  work_calibrator_t cal;
  double best_cv = 1e30, best_k = 0;
  calibration_result_t best_fit;
  for (double k : ks) {
    std::vector<calibration_sample_t> samples;
    samples.reserve(rows.size());
    for (const auto& r : rows) {
      std::vector<double> raw(r.feat.begin() + 1, r.feat.end());
      double excess = use_hinge ? std::max(0.0, raw.back() - k * r.g.warp_capacity) : 0.0;
      calibration_sample_t s;
      s.instance               = r.instance;
      s.features               = device_terms(raw, r.g, excess, r.max_row);
      s.measured_time_per_iter = r.measured;
      samples.push_back(std::move(s));
    }
    auto fit  = cal.fit(samples, n_terms, work_calibrator_t::options_t{});
    double cv = device_cv(rows, fit.coeffs, k, use_hinge);
    std::printf("  [grid] k=%.2f -> CV=%.4f\n", k, cv);
    if (cv < best_cv) {
      best_cv  = cv;
      best_k   = k;
      best_fit = fit;
    }
  }
  std::printf("\n=== %s device-aware fit ===\nrows=%zu best_k=%.2f COMBINED CV=%.4f\n",
              algo.c_str(),
              rows.size(),
              best_k,
              best_cv);
  // Per-GPU CV breakdown (cross-GPU generality check).
  std::vector<std::string> gpus;
  for (const auto& r : rows) {
    if (std::find(gpus.begin(), gpus.end(), std::string(r.g.name)) == gpus.end())
      gpus.push_back(r.g.name);
  }
  for (const auto& gn : gpus) {
    std::printf("  [per-gpu] %-28s CV=%.4f\n",
                gn.c_str(),
                device_cv(rows, best_fit.coeffs, best_k, use_hinge, gn));
  }

  const std::string out =
    "cpp/src/mip_heuristics/deterministic_calibrator/generated/" + algo + "_device_coeffs.hpp";
  std::ofstream f(out);
  f << "/* clang-format off */\n/*\n * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA "
       "CORPORATION & AFFILIATES. All rights reserved.\n * SPDX-License-Identifier: Apache-2.0\n "
       "*\n";
  f << " * AUTO-GENERATED by mip_work_calibrator (device-aware, multi-GPU). Do not edit by hand.\n";
  f << " * Algorithm: " << algo << "   GPU-generic (coeffs divide device rates at runtime)\n";
  f << " * Combined CV: " << best_cv << "   hinge_k: " << best_k << "\n";
  f << " */\n/* clang-format on */\n#pragma once\n\n#include <array>\n\n";
  f << "namespace cuopt::linear_programming::detail::calib {\n\n";
  f << "constexpr double " << algo << "_device_hinge_k = " << best_k << ";\n";
  f << "constexpr bool " << algo << "_device_use_hinge = " << (use_hinge ? "true" : "false")
    << ";\n\n";
  f << "constexpr std::array<double, " << best_fit.coeffs.size() << "> " << algo
    << "_device_coeffs = {\n";
  for (double c : best_fit.coeffs)
    f << "  " << c << ",\n";
  f << "};\n\n}  // namespace cuopt::linear_programming::detail::calib\n";
  std::printf("Wrote %s\n", out.c_str());
}

}  // namespace

int main(int argc, char** argv)
{
  std::string cmd = argc > 1 ? argv[1] : "fj";

  // Multi-GPU device-aware calibration commands.
  if (cmd == "dump") {
    // dump <algo> <dataset_dir> <csv_out>
    std::string algo    = argc > 2 ? argv[2] : "pdlp";
    std::string dataset = argc > 3 ? argv[3] : "datasets/mip/miplib2017";
    std::string csv     = argc > 4 ? argv[4] : "/tmp/calib_samples.csv";
    std::printf("=== dump %s -> %s ===\n", algo.c_str(), csv.c_str());
    dump_mode(algo, dataset, csv);
    return 0;
  }
  if (cmd == "fit") {
    // fit <algo> <csv1> [csv2 ...]
    std::string algo = argc > 2 ? argv[2] : "pdlp";
    std::vector<std::string> csvs;
    for (int i = 3; i < argc; ++i)
      csvs.push_back(argv[i]);
    if (csvs.empty()) csvs.push_back("/tmp/calib_samples.csv");
    std::printf("=== fit %s (device-aware, %zu csv) ===\n", algo.c_str(), csvs.size());
    fit_single_device(algo, csvs);
    return 0;
  }

  std::string algo        = cmd;
  std::string dataset_dir = argc > 2 ? argv[2] : "datasets/mip/miplib2017";
  std::string out_header  = argc > 3 ? argv[3] : std::string();

  std::printf("=== deterministic work-unit calibration: %s ===\n", algo.c_str());
  std::printf("dataset_dir: %s\n", dataset_dir.c_str());

  if (algo == "gpuinfo") {
    print_gpu_features(query_gpu_features(0));
  } else if (algo == "fj") {
    run_fj(dataset_dir, out_header);
  } else if (algo == "bp") {
    run_bp(dataset_dir, out_header);
  } else if (algo == "pdlp") {
    run_pdlp(dataset_dir, out_header);
  } else if (algo == "mp") {
    run_mp(dataset_dir, out_header);
  } else if (algo == "repair") {
    run_repair(dataset_dir, out_header);
  } else if (algo == "fpverify") {
    int npass = 0, ntot = 0;
    for (const auto& name : kInstances) {
      const std::string path = dataset_dir + "/" + name + ".mps";
      try {
        ++ntot;
        if (run_fp_verify(path, name)) { ++npass; }
      } catch (const std::exception& e) {
        std::printf("[%s] SKIP (%s)\n", name.c_str(), e.what());
        --ntot;
      }
    }
    std::printf("\n=== fpverify: %d/%d instances fully reproducible ===\n", npass, ntot);
  } else {
    std::printf("Unknown algo '%s' (expected fj|bp|pdlp|mp|repair|fpverify)\n", algo.c_str());
    return 2;
  }
  return 0;
}
